apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-db
  labels:
    app: app-db
spec:
  # nested `replica-set` definition
  replicas: 1
  selector:
    matchLabels:
      app: app-db
  template:
    metadata:
      labels:
        app: app-db
    spec:
      # nested `pod` definition
      containers:
      - image: app-db
        name: app-db
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-db
                key: password-secret
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        resources: {}
        volumeMounts:
          - name: app-db-persistent-storage
            mountPath: /var/lib/mysql
      restartPolicy: Always
      volumes:
        - name: app-db-persistent-storage
          persistentVolumeClaim:
            claimName: app-db-volumeclaim
status: {}
