apiVersion: v1
kind: Service
metadata:
  name: app-rest-api
  labels:
    app: app-rest-api
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: LoadBalancer
  ports:
  - name: "8888"
    port: 8888
    targetPort: 8888
  selector:
    app: app-rest-api
