apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-rest-api
  labels:
    app: app-rest-api
spec:
  # nested `replica-set` definition
  replicas: 1
  selector:
    matchLabels:
      app: app-rest-api
  template:
    metadata:
      labels:
        app: app-rest-api
    spec:
      # nested `pod` definition
      containers:
      - image: app-rest-api
        imagePullPolicy: IfNotPresent
        name: app-rest-api
        ports:
        - containerPort: 8888
        resources: {}
      restartPolicy: Always
status: {}
